###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
"name": "Posteo",
"age": 21,
"email":"Posteo@gmail.com"
}

###
POST http://localhost:9000/api/data HTTP/1.1
Content-Type: application/json

{
"name": "Datos",
"age": 31,
"email":"Minutos@gmail.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/63717b55be196942d16b3a22 HTTP/1.1

###
PUT http://localhost:9000/api/users/63717b55be196942d16b3a22 HTTP/1.1
Content-Type: application/json

{
"name": "Minutos Recontra Locos",
"age": 31,
"email":"Minutos@gmail.com"
}

###
DELETE http://localhost:9000/api/users/63717b55be196942d16b3a22 HTTP/1.1